# Generated by Django 5.0 on 2023-12-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adasdsad',
        ),
    ]
