# Generated by Django 5.0 on 2023-12-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('euroleague', '0002_delete_adasdsad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='belekas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Miesto pavadinimas', max_length=200)),
            ],
            options={
                'verbose_name': 'Miestas',
                'verbose_name_plural': 'Miestai',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lygos pavadinimas', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Lygos aprašymas', max_length=1000)),
            ],
            options={
                'verbose_name': 'Lyga',
                'verbose_name_plural': 'Lygos',
            },
        ),
        migrations.CreateModel(
            name='Profilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuotrauka', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilis',
                'verbose_name_plural': 'Profilis',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Komandos pavadinimas', max_length=200)),
                ('summary', models.TextField(help_text='Komandos aprašymas', max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos')),
                ('tm_code', models.IntegerField(help_text='Team Code used for predictions', null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='euroleague.city')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='euroleague.league')),
            ],
            options={
                'verbose_name': 'Komanda',
                'verbose_name_plural': 'Komandos',
            },
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home_game', models.BooleanField(default=True)),
                ('round_number', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('total_rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('pir', models.FloatField(default=0.0)),
                ('opponent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_stats', to='euroleague.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='euroleague.team')),
            ],
            options={
                'verbose_name': 'Komandų statistika',
                'verbose_name_plural': 'Komandų statistika',
            },
        ),
    ]
