# Generated by Django 5.0 on 2023-12-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='is_home_game',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='opponent_team',
        ),
    ]
