# Generated by Django 5.0 on 2023-12-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0004_remove_gamestats_is_home_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='is_home_game',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='opponent_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_stats', to='euroleague.team'),
        ),
    ]
