# Generated by Django 5.0 on 2023-12-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0005_gamestats_is_home_game_gamestats_opponent_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='is_home_game',
            field=models.CharField(default=True, max_length=5),
        ),
    ]
