# Generated by Django 5.0 on 2023-12-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0006_alter_gamestats_is_home_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='is_home_game',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='pir',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='points',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='steals',
        ),
        migrations.RemoveField(
            model_name='gamestats',
            name='total_rebounds',
        ),
        migrations.AddField(
            model_name='gamestats',
            name='assists_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='assists_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='blocks_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='blocks_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='field_goals_made_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='field_goals_made_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='opp_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='pir_away',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='pir_home',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='points_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='points_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='steals_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='steals_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='tm_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='total_rebounds_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='total_rebounds_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='win_loss',
            field=models.CharField(default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='opponent_team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_stats', to='euroleague.team'),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_stats', to='euroleague.team'),
        ),
    ]
