# Generated by Django 5.0 on 2023-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0007_remove_gamestats_assists_remove_gamestats_blocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroLeagueFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('fact_category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
