# Generated by Django 5.0 on 2023-12-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0008_euroleaguefact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={},
        ),
    ]
