# Generated by Django 5.0 on 2023-12-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0010_delete_belekas_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='euroleaguefact',
            options={'verbose_name': 'Fun facts', 'verbose_name_plural': 'Fun facts'},
        ),
        migrations.AlterModelOptions(
            name='gamestats',
            options={'verbose_name': 'Game stats', 'verbose_name_plural': 'Game stats'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'City', 'verbose_name_plural': 'City'},
        ),
    ]
