# Generated by Django 5.0 on 2023-12-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euroleague', '0012_alter_city_options_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='summary',
            field=models.TextField(help_text='Team summary', max_length=3000),
        ),
    ]
